import os

files = {}

files["Shared/NavMenu.razor"] = (
'<div class="top-row ps-3 navbar navbar-dark">\n'
'    <div class="container-fluid">\n'
'        <a class="navbar-brand" href="">GymBudgetApp</a>\n'
'        <button title="Navigation menu" class="navbar-toggler" @onclick="ToggleNavMenu">\n'
'            <span class="navbar-toggler-icon"></span>\n'
'        </button>\n'
'    </div>\n'
'</div>\n'
'<div class="@NavMenuCssClass nav-scrollable" @onclick="ToggleNavMenu">\n'
'    <nav class="flex-column">\n'
'        <div class="nav-item px-3">\n'
'            <NavLink class="nav-link" href="" Match="NavLinkMatch.All">\n'
'                <span class="oi oi-home" aria-hidden="true"></span> Dashboard\n'
'            </NavLink>\n'
'        </div>\n'
'        <div class="nav-item px-3">\n'
'            <NavLink class="nav-link" href="seasons">\n'
'                <span class="oi oi-calendar" aria-hidden="true"></span> Seasons\n'
'            </NavLink>\n'
'        </div>\n'
'        <div class="nav-item px-3">\n'
'            <NavLink class="nav-link" href="meets">\n'
'                <span class="oi oi-map-marker" aria-hidden="true"></span> Meets\n'
'            </NavLink>\n'
'        </div>\n'
'        <div class="nav-item px-3">\n'
'            <NavLink class="nav-link" href="coaches">\n'
'                <span class="oi oi-people" aria-hidden="true"></span> Coaches\n'
'            </NavLink>\n'
'        </div>\n'
'        <div class="nav-item px-3">\n'
'            <NavLink class="nav-link" href="budget">\n'
'                <span class="oi oi-dollar" aria-hidden="true"></span> Budget\n'
'            </NavLink>\n'
'        </div>\n'
'        <div class="nav-item px-3">\n'
'            <NavLink class="nav-link" href="perdiem">\n'
'                <span class="oi oi-fork" aria-hidden="true"></span> Per Diem\n'
'            </NavLink>\n'
'        </div>\n'
'        <div class="nav-item px-3">\n'
'            <NavLink class="nav-link" href="teamlevels">\n'
'                <span class="oi oi-star" aria-hidden="true"></span> Team Levels\n'
'            </NavLink>\n'
'        </div>\n'
'        <div class="nav-item px-3">\n'
'            <NavLink class="nav-link" href="reports">\n'
'                <span class="oi oi-document" aria-hidden="true"></span> Reports\n'
'            </NavLink>\n'
'        </div>\n'
'    </nav>\n'
'</div>\n'
'@code {\n'
'    private bool collapseNavMenu = true;\n'
'    private string? NavMenuCssClass => collapseNavMenu ? "collapse" : null;\n'
'    private void ToggleNavMenu()\n'
'    {\n'
'        collapseNavMenu = !collapseNavMenu;\n'
'    }\n'
'}\n'
)

for path, content in files.items():
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    size = os.path.getsize(path)
    print(f"Written {path} ({size} bytes)")
