import os

files = {}

files["Pages/Coaches.razor"] = (
'@page "/coaches"\n'
'@using GymBudgetApp.Models\n'
'@using GymBudgetApp\n'
'@using Microsoft.EntityFrameworkCore\n'
'@inject AppDbContext Db\n'
'\n'
'<h3>Coaches</h3>\n'
'\n'
'@if (seasons == null)\n'
'{\n'
'    <p>Loading...</p>\n'
'}\n'
'else\n'
'{\n'
'    <div class="mb-3">\n'
'        <label>Select Season</label>\n'
'        <select class="form-select w-auto d-inline-block ms-2" @onchange="OnSeasonChanged">\n'
'            <option value="">-- Select Season --</option>\n'
'            @foreach (var s in seasons)\n'
'            {\n'
'                <option value="@s.Id">@s.Name</option>\n'
'            }\n'
'        </select>\n'
'    </div>\n'
'\n'
'    @if (selectedSeasonId > 0)\n'
'    {\n'
'        <button class="btn btn-primary mb-3" @onclick="ShowForm">+ Add Coach</button>\n'
'\n'
'        @if (showForm)\n'
'        {\n'
'            <div class="card mb-4 p-3">\n'
'                <h5>@(editingCoach == null ? "Add Coach" : "Edit Coach")</h5>\n'
'                <div class="mb-2">\n'
'                    <label>Name</label>\n'
'                    <input class="form-control" @bind="formName" />\n'
'                </div>\n'
'                <div class="mb-2">\n'
'                    <label>Role</label>\n'
'                    <input class="form-control" @bind="formRole" placeholder="e.g. Head Coach, Compulsory 1" />\n'
'                </div>\n'
'                <div class="mb-2">\n'
'                    <input type="checkbox" @bind="formIsActive" /> Active\n'
'                </div>\n'
'                <button class="btn btn-success me-2" @onclick="SaveCoach">Save</button>\n'
'                <button class="btn btn-secondary" @onclick="CancelForm">Cancel</button>\n'
'            </div>\n'
'        }\n'
'\n'
'        <table class="table table-striped">\n'
'            <thead>\n'
'                <tr>\n'
'                    <th>Name</th>\n'
'                    <th>Role</th>\n'
'                    <th>Status</th>\n'
'                    <th>Actions</th>\n'
'                </tr>\n'
'            </thead>\n'
'            <tbody>\n'
'                @foreach (var coach in coaches)\n'
'                {\n'
'                    <tr>\n'
'                        <td>@coach.Name</td>\n'
'                        <td>@coach.Role</td>\n'
'                        <td>\n'
'                            @if (coach.IsActive)\n'
'                            {\n'
'                                <span class="badge bg-success">Active</span>\n'
'                            }\n'
'                            else\n'
'                            {\n'
'                                <span class="badge bg-secondary">Inactive</span>\n'
'                            }\n'
'                        </td>\n'
'                        <td>\n'
'                            <button class="btn btn-sm btn-outline-primary me-1" @onclick="() => EditCoach(coach)">Edit</button>\n'
'                            <button class="btn btn-sm btn-outline-danger" @onclick="() => DeleteCoach(coach)">Delete</button>\n'
'                        </td>\n'
'                    </tr>\n'
'                }\n'
'            </tbody>\n'
'        </table>\n'
'    }\n'
'}\n'
'\n'
'@code {\n'
'    private List<Season>? seasons;\n'
'    private List<Coach> coaches = new();\n'
'    private int selectedSeasonId;\n'
'    private bool showForm;\n'
'    private Coach? editingCoach;\n'
'    private string formName = "";\n'
'    private string formRole = "";\n'
'    private bool formIsActive = true;\n'
'\n'
'    protected override async Task OnInitializedAsync()\n'
'    {\n'
'        seasons = await Task.FromResult(Db.Seasons.OrderByDescending(s => s.Name).ToList());\n'
'        var active = seasons.FirstOrDefault(s => s.IsActive);\n'
'        if (active != null) { selectedSeasonId = active.Id; await LoadCoaches(); }\n'
'    }\n'
'\n'
'    private async Task OnSeasonChanged(ChangeEventArgs e)\n'
'    {\n'
'        selectedSeasonId = int.TryParse(e.Value?.ToString(), out var id) ? id : 0;\n'
'        await LoadCoaches();\n'
'    }\n'
'\n'
'    private async Task LoadCoaches()\n'
'    {\n'
'        coaches = await Task.FromResult(Db.Coaches.Where(c => c.SeasonId == selectedSeasonId).ToList());\n'
'    }\n'
'\n'
'    private void ShowForm() { editingCoach = null; formName = ""; formRole = ""; formIsActive = true; showForm = true; }\n'
'    private void CancelForm() { showForm = false; }\n'
'\n'
'    private void EditCoach(Coach coach)\n'
'    {\n'
'        editingCoach = coach; formName = coach.Name; formRole = coach.Role; formIsActive = coach.IsActive; showForm = true;\n'
'    }\n'
'\n'
'    private async Task SaveCoach()\n'
'    {\n'
'        if (editingCoach == null)\n'
'        {\n'
'            Db.Coaches.Add(new Coach { Name = formName, Role = formRole, IsActive = formIsActive, SeasonId = selectedSeasonId });\n'
'        }\n'
'        else\n'
'        {\n'
'            editingCoach.Name = formName; editingCoach.Role = formRole; editingCoach.IsActive = formIsActive;\n'
'            Db.Coaches.Update(editingCoach);\n'
'        }\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadCoaches();\n'
'        showForm = false;\n'
'    }\n'
'\n'
'    private async Task DeleteCoach(Coach coach)\n'
'    {\n'
'        Db.Coaches.Remove(coach);\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadCoaches();\n'
'    }\n'
'}\n'
)

files["Pages/Meets.razor"] = (
'@page "/meets"\n'
'@using GymBudgetApp.Models\n'
'@using GymBudgetApp\n'
'@inject AppDbContext Db\n'
'\n'
'<h3>Meets</h3>\n'
'\n'
'@if (seasons == null)\n'
'{\n'
'    <p>Loading...</p>\n'
'}\n'
'else\n'
'{\n'
'    <div class="mb-3">\n'
'        <label>Select Season</label>\n'
'        <select class="form-select w-auto d-inline-block ms-2" @onchange="OnSeasonChanged">\n'
'            <option value="">-- Select Season --</option>\n'
'            @foreach (var s in seasons)\n'
'            {\n'
'                <option value="@s.Id">@s.Name</option>\n'
'            }\n'
'        </select>\n'
'    </div>\n'
'\n'
'    @if (selectedSeasonId > 0)\n'
'    {\n'
'        <button class="btn btn-primary mb-3" @onclick="ShowForm">+ Add Meet</button>\n'
'\n'
'        @if (showForm)\n'
'        {\n'
'            <div class="card mb-4 p-3">\n'
'                <h5>@(editingMeet == null ? "Add Meet" : "Edit Meet")</h5>\n'
'                <div class="mb-2">\n'
'                    <label>Meet Name</label>\n'
'                    <input class="form-control" @bind="formName" placeholder="e.g. Meet 1, State Meet" />\n'
'                </div>\n'
'                <div class="mb-2">\n'
'                    <label>Date</label>\n'
'                    <input type="date" class="form-control" @bind="formDate" />\n'
'                </div>\n'
'                <div class="mb-2">\n'
'                    <label>Travel Type</label>\n'
'                    <select class="form-select" @bind="formTravelType">\n'
'                        <option value="Drive">Drive</option>\n'
'                        <option value="Fly">Fly</option>\n'
'                    </select>\n'
'                </div>\n'
'                <button class="btn btn-success me-2" @onclick="SaveMeet">Save</button>\n'
'                <button class="btn btn-secondary" @onclick="CancelForm">Cancel</button>\n'
'            </div>\n'
'        }\n'
'\n'
'        <table class="table table-striped">\n'
'            <thead>\n'
'                <tr>\n'
'                    <th>Meet Name</th>\n'
'                    <th>Date</th>\n'
'                    <th>Travel</th>\n'
'                    <th>Actions</th>\n'
'                </tr>\n'
'            </thead>\n'
'            <tbody>\n'
'                @foreach (var meet in meets)\n'
'                {\n'
'                    <tr>\n'
'                        <td>@meet.Name</td>\n'
'                        <td>@meet.Date.ToString("MM/dd/yyyy")</td>\n'
'                        <td>\n'
'                            @if (meet.TravelType == TravelType.Fly)\n'
'                            {\n'
'                                <span class="badge bg-info text-dark">Fly</span>\n'
'                            }\n'
'                            else\n'
'                            {\n'
'                                <span class="badge bg-secondary">Drive</span>\n'
'                            }\n'
'                        </td>\n'
'                        <td>\n'
'                            <button class="btn btn-sm btn-outline-primary me-1" @onclick="() => EditMeet(meet)">Edit</button>\n'
'                            <button class="btn btn-sm btn-outline-danger" @onclick="() => DeleteMeet(meet)">Delete</button>\n'
'                        </td>\n'
'                    </tr>\n'
'                }\n'
'            </tbody>\n'
'        </table>\n'
'    }\n'
'}\n'
'\n'
'@code {\n'
'    private List<Season>? seasons;\n'
'    private List<Meet> meets = new();\n'
'    private int selectedSeasonId;\n'
'    private bool showForm;\n'
'    private Meet? editingMeet;\n'
'    private string formName = "";\n'
'    private DateTime formDate = DateTime.Today;\n'
'    private TravelType formTravelType = TravelType.Drive;\n'
'\n'
'    protected override async Task OnInitializedAsync()\n'
'    {\n'
'        seasons = await Task.FromResult(Db.Seasons.OrderByDescending(s => s.Name).ToList());\n'
'        var active = seasons.FirstOrDefault(s => s.IsActive);\n'
'        if (active != null) { selectedSeasonId = active.Id; await LoadMeets(); }\n'
'    }\n'
'\n'
'    private async Task OnSeasonChanged(ChangeEventArgs e)\n'
'    {\n'
'        selectedSeasonId = int.TryParse(e.Value?.ToString(), out var id) ? id : 0;\n'
'        await LoadMeets();\n'
'    }\n'
'\n'
'    private async Task LoadMeets()\n'
'    {\n'
'        meets = await Task.FromResult(Db.Meets.Where(m => m.SeasonId == selectedSeasonId).OrderBy(m => m.Date).ToList());\n'
'    }\n'
'\n'
'    private void ShowForm() { editingMeet = null; formName = ""; formDate = DateTime.Today; formTravelType = TravelType.Drive; showForm = true; }\n'
'    private void CancelForm() { showForm = false; }\n'
'\n'
'    private void EditMeet(Meet meet)\n'
'    {\n'
'        editingMeet = meet; formName = meet.Name; formDate = meet.Date; formTravelType = meet.TravelType; showForm = true;\n'
'    }\n'
'\n'
'    private async Task SaveMeet()\n'
'    {\n'
'        if (editingMeet == null)\n'
'        {\n'
'            Db.Meets.Add(new Meet { Name = formName, Date = formDate, TravelType = formTravelType, SeasonId = selectedSeasonId });\n'
'        }\n'
'        else\n'
'        {\n'
'            editingMeet.Name = formName; editingMeet.Date = formDate; editingMeet.TravelType = formTravelType;\n'
'            Db.Meets.Update(editingMeet);\n'
'        }\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadMeets();\n'
'        showForm = false;\n'
'    }\n'
'\n'
'    private async Task DeleteMeet(Meet meet)\n'
'    {\n'
'        Db.Meets.Remove(meet);\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadMeets();\n'
'    }\n'
'}\n'
)

files["Pages/Budget.razor"] = (
'@page "/budget"\n'
'@using GymBudgetApp.Models\n'
'@using GymBudgetApp\n'
'@inject AppDbContext Db\n'
'\n'
'<h3>Budget</h3>\n'
'\n'
'@if (seasons == null)\n'
'{\n'
'    <p>Loading...</p>\n'
'}\n'
'else\n'
'{\n'
'    <div class="mb-3">\n'
'        <label>Select Season</label>\n'
'        <select class="form-select w-auto d-inline-block ms-2" @onchange="OnSeasonChanged">\n'
'            <option value="">-- Select Season --</option>\n'
'            @foreach (var s in seasons)\n'
'            {\n'
'                <option value="@s.Id">@s.Name</option>\n'
'            }\n'
'        </select>\n'
'    </div>\n'
'\n'
'    @if (selectedSeasonId > 0)\n'
'    {\n'
'        <div class="row mb-3">\n'
'            <div class="col-md-4">\n'
'                <div class="card text-white bg-primary">\n'
'                    <div class="card-body">\n'
'                        <h6>Total Budgeted</h6>\n'
'                        <h4>@budgetTotal.ToString("C")</h4>\n'
'                    </div>\n'
'                </div>\n'
'            </div>\n'
'            <div class="col-md-4">\n'
'                <div class="card text-white bg-success">\n'
'                    <div class="card-body">\n'
'                        <h6>Total Actual</h6>\n'
'                        <h4>@actualTotal.ToString("C")</h4>\n'
'                    </div>\n'
'                </div>\n'
'            </div>\n'
'            <div class="col-md-4">\n'
'                <div class="card text-white bg-info">\n'
'                    <div class="card-body">\n'
'                        <h6>Cost Per Athlete</h6>\n'
'                        <h4>@costPerAthlete.ToString("C")</h4>\n'
'                    </div>\n'
'                </div>\n'
'            </div>\n'
'        </div>\n'
'\n'
'        <button class="btn btn-primary mb-3" @onclick="ShowForm">+ Add Line Item</button>\n'
'\n'
'        @if (showForm)\n'
'        {\n'
'            <div class="card mb-4 p-3">\n'
'                <h5>@(editingItem == null ? "Add Line Item" : "Edit Line Item")</h5>\n'
'                <div class="row">\n'
'                    <div class="col-md-3 mb-2">\n'
'                        <label>Category</label>\n'
'                        <select class="form-select" @bind="formCategory">\n'
'                            @foreach (var cat in Enum.GetValues<BudgetCategory>())\n'
'                            {\n'
'                                <option value="@cat">@cat</option>\n'
'                            }\n'
'                        </select>\n'
'                    </div>\n'
'                    <div class="col-md-3 mb-2">\n'
'                        <label>Meet (optional)</label>\n'
'                        <select class="form-select" @bind="formMeetId">\n'
'                            <option value="0">Season-wide</option>\n'
'                            @foreach (var m in meets)\n'
'                            {\n'
'                                <option value="@m.Id">@m.Name</option>\n'
'                            }\n'
'                        </select>\n'
'                    </div>\n'
'                    <div class="col-md-2 mb-2">\n'
'                        <label>Rate ($)</label>\n'
'                        <input type="number" step="0.01" class="form-control" @bind="formRate" />\n'
'                    </div>\n'
'                    <div class="col-md-2 mb-2">\n'
'                        <label>Quantity</label>\n'
'                        <input type="number" step="0.01" class="form-control" @bind="formQuantity" />\n'
'                    </div>\n'
'                    <div class="col-md-2 mb-2">\n'
'                        <label>Type</label>\n'
'                        <select class="form-select" @bind="formIsActual">\n'
'                            <option value="false">Budgeted</option>\n'
'                            <option value="true">Actual</option>\n'
'                        </select>\n'
'                    </div>\n'
'                </div>\n'
'                <div class="mb-2">\n'
'                    <label>Notes</label>\n'
'                    <input class="form-control" @bind="formNotes" />\n'
'                </div>\n'
'                <button class="btn btn-success me-2" @onclick="SaveItem">Save</button>\n'
'                <button class="btn btn-secondary" @onclick="CancelForm">Cancel</button>\n'
'            </div>\n'
'        }\n'
'\n'
'        <ul class="nav nav-tabs mb-3">\n'
'            <li class="nav-item">\n'
'                <button class="nav-link @(showActual == false ? "active" : "")" @onclick="() => showActual = false">Budgeted</button>\n'
'            </li>\n'
'            <li class="nav-item">\n'
'                <button class="nav-link @(showActual == true ? "active" : "")" @onclick="() => showActual = true">Actual</button>\n'
'            </li>\n'
'        </ul>\n'
'\n'
'        <table class="table table-striped">\n'
'            <thead>\n'
'                <tr>\n'
'                    <th>Category</th>\n'
'                    <th>Meet</th>\n'
'                    <th>Rate</th>\n'
'                    <th>Qty</th>\n'
'                    <th>Total</th>\n'
'                    <th>Notes</th>\n'
'                    <th>Actions</th>\n'
'                </tr>\n'
'            </thead>\n'
'            <tbody>\n'
'                @foreach (var item in lineItems.Where(i => i.IsActual == showActual))\n'
'                {\n'
'                    <tr>\n'
'                        <td>@item.Category</td>\n'
'                        <td>@(item.MeetId.HasValue ? meets.FirstOrDefault(m => m.Id == item.MeetId)?.Name : "Season-wide")</td>\n'
'                        <td>@item.Rate.ToString("C")</td>\n'
'                        <td>@item.Quantity</td>\n'
'                        <td>@item.Total.ToString("C")</td>\n'
'                        <td>@item.Notes</td>\n'
'                        <td>\n'
'                            <button class="btn btn-sm btn-outline-primary me-1" @onclick="() => EditItem(item)">Edit</button>\n'
'                            <button class="btn btn-sm btn-outline-danger" @onclick="() => DeleteItem(item)">Delete</button>\n'
'                        </td>\n'
'                    </tr>\n'
'                }\n'
'            </tbody>\n'
'            <tfoot>\n'
'                <tr class="fw-bold">\n'
'                    <td colspan="4">Total</td>\n'
'                    <td>@lineItems.Where(i => i.IsActual == showActual).Sum(i => i.Total).ToString("C")</td>\n'
'                    <td colspan="2"></td>\n'
'                </tr>\n'
'            </tfoot>\n'
'        </table>\n'
'    }\n'
'}\n'
'\n'
'@code {\n'
'    private List<Season>? seasons;\n'
'    private List<Meet> meets = new();\n'
'    private List<BudgetLineItem> lineItems = new();\n'
'    private int selectedSeasonId;\n'
'    private bool showForm;\n'
'    private bool showActual = false;\n'
'    private BudgetLineItem? editingItem;\n'
'    private BudgetCategory formCategory = BudgetCategory.TeamEntry;\n'
'    private int formMeetId = 0;\n'
'    private decimal formRate = 0;\n'
'    private decimal formQuantity = 0;\n'
'    private bool formIsActual = false;\n'
'    private string formNotes = "";\n'
'\n'
'    private decimal budgetTotal => lineItems.Where(i => !i.IsActual).Sum(i => i.Total);\n'
'    private decimal actualTotal => lineItems.Where(i => i.IsActual).Sum(i => i.Total);\n'
'    private decimal costPerAthlete => selectedSeason?.AthleteCount > 0 ? budgetTotal / selectedSeason!.AthleteCount : 0;\n'
'    private Season? selectedSeason;\n'
'\n'
'    protected override async Task OnInitializedAsync()\n'
'    {\n'
'        seasons = await Task.FromResult(Db.Seasons.OrderByDescending(s => s.Name).ToList());\n'
'        var active = seasons.FirstOrDefault(s => s.IsActive);\n'
'        if (active != null) { selectedSeasonId = active.Id; selectedSeason = active; await LoadData(); }\n'
'    }\n'
'\n'
'    private async Task OnSeasonChanged(ChangeEventArgs e)\n'
'    {\n'
'        selectedSeasonId = int.TryParse(e.Value?.ToString(), out var id) ? id : 0;\n'
'        selectedSeason = seasons?.FirstOrDefault(s => s.Id == selectedSeasonId);\n'
'        await LoadData();\n'
'    }\n'
'\n'
'    private async Task LoadData()\n'
'    {\n'
'        meets = await Task.FromResult(Db.Meets.Where(m => m.SeasonId == selectedSeasonId).OrderBy(m => m.Date).ToList());\n'
'        lineItems = await Task.FromResult(Db.BudgetLineItems.Where(b => b.SeasonId == selectedSeasonId).ToList());\n'
'    }\n'
'\n'
'    private void ShowForm() { editingItem = null; formCategory = BudgetCategory.TeamEntry; formMeetId = 0; formRate = 0; formQuantity = 0; formIsActual = false; formNotes = ""; showForm = true; }\n'
'    private void CancelForm() { showForm = false; }\n'
'\n'
'    private void EditItem(BudgetLineItem item)\n'
'    {\n'
'        editingItem = item; formCategory = item.Category; formMeetId = item.MeetId ?? 0;\n'
'        formRate = item.Rate; formQuantity = item.Quantity; formIsActual = item.IsActual; formNotes = item.Notes ?? ""; showForm = true;\n'
'    }\n'
'\n'
'    private async Task SaveItem()\n'
'    {\n'
'        if (editingItem == null)\n'
'        {\n'
'            Db.BudgetLineItems.Add(new BudgetLineItem\n'
'            {\n'
'                Category = formCategory, MeetId = formMeetId > 0 ? formMeetId : null,\n'
'                Rate = formRate, Quantity = formQuantity, IsActual = formIsActual,\n'
'                Notes = formNotes, SeasonId = selectedSeasonId\n'
'            });\n'
'        }\n'
'        else\n'
'        {\n'
'            editingItem.Category = formCategory; editingItem.MeetId = formMeetId > 0 ? formMeetId : null;\n'
'            editingItem.Rate = formRate; editingItem.Quantity = formQuantity;\n'
'            editingItem.IsActual = formIsActual; editingItem.Notes = formNotes;\n'
'            Db.BudgetLineItems.Update(editingItem);\n'
'        }\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadData();\n'
'        showForm = false;\n'
'    }\n'
'\n'
'    private async Task DeleteItem(BudgetLineItem item)\n'
'    {\n'
'        Db.BudgetLineItems.Remove(item);\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadData();\n'
'    }\n'
'}\n'
)

files["Pages/PerDiem.razor"] = (
'@page "/perdiem"\n'
'@using GymBudgetApp.Models\n'
'@using GymBudgetApp\n'
'@inject AppDbContext Db\n'
'\n'
'<h3>Per Diem</h3>\n'
'\n'
'@if (seasons == null)\n'
'{\n'
'    <p>Loading...</p>\n'
'}\n'
'else\n'
'{\n'
'    <div class="mb-3">\n'
'        <label>Select Season</label>\n'
'        <select class="form-select w-auto d-inline-block ms-2" @onchange="OnSeasonChanged">\n'
'            <option value="">-- Select Season --</option>\n'
'            @foreach (var s in seasons)\n'
'            {\n'
'                <option value="@s.Id">@s.Name</option>\n'
'            }\n'
'        </select>\n'
'    </div>\n'
'\n'
'    @if (selectedSeasonId > 0)\n'
'    {\n'
'        <div class="mb-3">\n'
'            <label>Select Meet</label>\n'
'            <select class="form-select w-auto d-inline-block ms-2" @onchange="OnMeetChanged">\n'
'                <option value="0">-- Select Meet --</option>\n'
'                @foreach (var m in meets)\n'
'                {\n'
'                    <option value="@m.Id">@m.Name</option>\n'
'                }\n'
'            </select>\n'
'        </div>\n'
'    }\n'
'\n'
'    @if (selectedMeetId > 0)\n'
'    {\n'
'        <button class="btn btn-primary mb-3" @onclick="ShowForm">+ Add Entry</button>\n'
'\n'
'        @if (showForm)\n'
'        {\n'
'            <div class="card mb-4 p-3">\n'
'                <h5>@(editingEntry == null ? "Add Per Diem Entry" : "Edit Entry")</h5>\n'
'                <div class="row">\n'
'                    <div class="col-md-3 mb-2">\n'
'                        <label>Coach</label>\n'
'                        <select class="form-select" @bind="formCoachId">\n'
'                            <option value="0">-- Select Coach --</option>\n'
'                            @foreach (var c in coaches)\n'
'                            {\n'
'                                <option value="@c.Id">@c.Name</option>\n'
'                            }\n'
'                        </select>\n'
'                    </div>\n'
'                    <div class="col-md-3 mb-2">\n'
'                        <label>Meal</label>\n'
'                        <select class="form-select" @bind="formMealType">\n'
'                            <option value="Breakfast">Breakfast</option>\n'
'                            <option value="Lunch">Lunch</option>\n'
'                            <option value="Dinner">Dinner</option>\n'
'                        </select>\n'
'                    </div>\n'
'                    <div class="col-md-2 mb-2">\n'
'                        <label>Rate ($)</label>\n'
'                        <input type="number" step="0.01" class="form-control" @bind="formRate" />\n'
'                    </div>\n'
'                    <div class="col-md-2 mb-2">\n'
'                        <label># of Days</label>\n'
'                        <input type="number" class="form-control" @bind="formDays" />\n'
'                    </div>\n'
'                    <div class="col-md-2 mb-2">\n'
'                        <label>Type</label>\n'
'                        <select class="form-select" @bind="formIsActual">\n'
'                            <option value="false">Budgeted</option>\n'
'                            <option value="true">Actual</option>\n'
'                        </select>\n'
'                    </div>\n'
'                </div>\n'
'                <button class="btn btn-success me-2" @onclick="SaveEntry">Save</button>\n'
'                <button class="btn btn-secondary" @onclick="CancelForm">Cancel</button>\n'
'            </div>\n'
'        }\n'
'\n'
'        <table class="table table-striped">\n'
'            <thead>\n'
'                <tr>\n'
'                    <th>Coach</th>\n'
'                    <th>Meal</th>\n'
'                    <th>Rate</th>\n'
'                    <th>Days</th>\n'
'                    <th>Total</th>\n'
'                    <th>Type</th>\n'
'                    <th>Actions</th>\n'
'                </tr>\n'
'            </thead>\n'
'            <tbody>\n'
'                @foreach (var entry in entries)\n'
'                {\n'
'                    <tr>\n'
'                        <td>@coaches.FirstOrDefault(c => c.Id == entry.CoachId)?.Name</td>\n'
'                        <td>@entry.MealType</td>\n'
'                        <td>@entry.Rate.ToString("C")</td>\n'
'                        <td>@entry.NumberOfDays</td>\n'
'                        <td>@entry.Total.ToString("C")</td>\n'
'                        <td>@(entry.IsActual ? "Actual" : "Budgeted")</td>\n'
'                        <td>\n'
'                            <button class="btn btn-sm btn-outline-primary me-1" @onclick="() => EditEntry(entry)">Edit</button>\n'
'                            <button class="btn btn-sm btn-outline-danger" @onclick="() => DeleteEntry(entry)">Delete</button>\n'
'                        </td>\n'
'                    </tr>\n'
'                }\n'
'            </tbody>\n'
'            <tfoot>\n'
'                <tr class="fw-bold">\n'
'                    <td colspan="4">Total</td>\n'
'                    <td>@entries.Sum(e => e.Total).ToString("C")</td>\n'
'                    <td colspan="2"></td>\n'
'                </tr>\n'
'            </tfoot>\n'
'        </table>\n'
'    }\n'
'}\n'
'\n'
'@code {\n'
'    private List<Season>? seasons;\n'
'    private List<Meet> meets = new();\n'
'    private List<Coach> coaches = new();\n'
'    private List<PerDiemEntry> entries = new();\n'
'    private int selectedSeasonId;\n'
'    private int selectedMeetId;\n'
'    private bool showForm;\n'
'    private PerDiemEntry? editingEntry;\n'
'    private int formCoachId = 0;\n'
'    private MealType formMealType = MealType.Breakfast;\n'
'    private decimal formRate = 0;\n'
'    private int formDays = 1;\n'
'    private bool formIsActual = false;\n'
'\n'
'    protected override async Task OnInitializedAsync()\n'
'    {\n'
'        seasons = await Task.FromResult(Db.Seasons.OrderByDescending(s => s.Name).ToList());\n'
'        var active = seasons.FirstOrDefault(s => s.IsActive);\n'
'        if (active != null) { selectedSeasonId = active.Id; await LoadMeets(); }\n'
'    }\n'
'\n'
'    private async Task OnSeasonChanged(ChangeEventArgs e)\n'
'    {\n'
'        selectedSeasonId = int.TryParse(e.Value?.ToString(), out var id) ? id : 0;\n'
'        selectedMeetId = 0;\n'
'        await LoadMeets();\n'
'    }\n'
'\n'
'    private async Task OnMeetChanged(ChangeEventArgs e)\n'
'    {\n'
'        selectedMeetId = int.TryParse(e.Value?.ToString(), out var id) ? id : 0;\n'
'        await LoadEntries();\n'
'    }\n'
'\n'
'    private async Task LoadMeets()\n'
'    {\n'
'        meets = await Task.FromResult(Db.Meets.Where(m => m.SeasonId == selectedSeasonId).OrderBy(m => m.Date).ToList());\n'
'        coaches = await Task.FromResult(Db.Coaches.Where(c => c.SeasonId == selectedSeasonId).ToList());\n'
'    }\n'
'\n'
'    private async Task LoadEntries()\n'
'    {\n'
'        entries = await Task.FromResult(Db.PerDiemEntries.Where(p => p.MeetId == selectedMeetId).ToList());\n'
'    }\n'
'\n'
'    private void ShowForm() { editingEntry = null; formCoachId = 0; formMealType = MealType.Breakfast; formRate = 0; formDays = 1; formIsActual = false; showForm = true; }\n'
'    private void CancelForm() { showForm = false; }\n'
'\n'
'    private void EditEntry(PerDiemEntry entry)\n'
'    {\n'
'        editingEntry = entry; formCoachId = entry.CoachId; formMealType = entry.MealType;\n'
'        formRate = entry.Rate; formDays = entry.NumberOfDays; formIsActual = entry.IsActual; showForm = true;\n'
'    }\n'
'\n'
'    private async Task SaveEntry()\n'
'    {\n'
'        if (editingEntry == null)\n'
'        {\n'
'            Db.PerDiemEntries.Add(new PerDiemEntry\n'
'            {\n'
'                CoachId = formCoachId, MealType = formMealType,\n'
'                Rate = formRate, NumberOfDays = formDays,\n'
'                IsActual = formIsActual, MeetId = selectedMeetId\n'
'            });\n'
'        }\n'
'        else\n'
'        {\n'
'            editingEntry.CoachId = formCoachId; editingEntry.MealType = formMealType;\n'
'            editingEntry.Rate = formRate; editingEntry.NumberOfDays = formDays;\n'
'            editingEntry.IsActual = formIsActual;\n'
'            Db.PerDiemEntries.Update(editingEntry);\n'
'        }\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadEntries();\n'
'        showForm = false;\n'
'    }\n'
'\n'
'    private async Task DeleteEntry(PerDiemEntry entry)\n'
'    {\n'
'        Db.PerDiemEntries.Remove(entry);\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadEntries();\n'
'    }\n'
'}\n'
)

files["Pages/TeamLevels.razor"] = (
'@page "/teamlevels"\n'
'@using GymBudgetApp.Models\n'
'@using GymBudgetApp\n'
'@inject AppDbContext Db\n'
'\n'
'<h3>Team Levels</h3>\n'
'\n'
'@if (seasons == null)\n'
'{\n'
'    <p>Loading...</p>\n'
'}\n'
'else\n'
'{\n'
'    <div class="mb-3">\n'
'        <label>Select Season</label>\n'
'        <select class="form-select w-auto d-inline-block ms-2" @onchange="OnSeasonChanged">\n'
'            <option value="">-- Select Season --</option>\n'
'            @foreach (var s in seasons)\n'
'            {\n'
'                <option value="@s.Id">@s.Name</option>\n'
'            }\n'
'        </select>\n'
'    </div>\n'
'\n'
'    @if (selectedSeasonId > 0)\n'
'    {\n'
'        <button class="btn btn-primary mb-3" @onclick="ShowForm">+ Add Team Level</button>\n'
'\n'
'        @if (showForm)\n'
'        {\n'
'            <div class="card mb-4 p-3">\n'
'                <h5>@(editingLevel == null ? "Add Team Level" : "Edit Team Level")</h5>\n'
'                <div class="row">\n'
'                    <div class="col-md-4 mb-2">\n'
'                        <label>Level Name</label>\n'
'                        <input class="form-control" @bind="formName" placeholder="e.g. Gym Stars, Elite/HOPE" />\n'
'                    </div>\n'
'                    <div class="col-md-4 mb-2">\n'
'                        <label>Athlete Count</label>\n'
'                        <input type="number" class="form-control" @bind="formAthleteCount" />\n'
'                    </div>\n'
'                    <div class="col-md-4 mb-2">\n'
'                        <label>Payment Plan (months)</label>\n'
'                        <input type="number" class="form-control" @bind="formPaymentMonths" />\n'
'                    </div>\n'
'                </div>\n'
'                <button class="btn btn-success me-2" @onclick="SaveLevel">Save</button>\n'
'                <button class="btn btn-secondary" @onclick="CancelForm">Cancel</button>\n'
'            </div>\n'
'        }\n'
'\n'
'        @foreach (var level in teamLevels)\n'
'        {\n'
'            <div class="card mb-3">\n'
'                <div class="card-header d-flex justify-content-between">\n'
'                    <h5>@level.Name — @level.AthleteCount athletes</h5>\n'
'                    <div>\n'
'                        <button class="btn btn-sm btn-outline-primary me-1" @onclick="() => EditLevel(level)">Edit</button>\n'
'                        <button class="btn btn-sm btn-outline-danger" @onclick="() => DeleteLevel(level)">Delete</button>\n'
'                    </div>\n'
'                </div>\n'
'                <div class="card-body">\n'
'                    <h6>Athlete Items</h6>\n'
'                    <table class="table table-sm">\n'
'                        <thead><tr><th>Item</th><th>Cost</th><th>Required</th><th></th></tr></thead>\n'
'                        <tbody>\n'
'                            @foreach (var item in athleteItems.Where(i => i.TeamLevelId == level.Id))\n'
'                            {\n'
'                                <tr>\n'
'                                    <td>@item.Name</td>\n'
'                                    <td>@item.Cost.ToString("C")</td>\n'
'                                    <td>@(item.IsRequired ? "Yes" : "No")</td>\n'
'                                    <td><button class="btn btn-sm btn-outline-danger" @onclick="() => DeleteAthleteItem(item)">Remove</button></td>\n'
'                                </tr>\n'
'                            }\n'
'                        </tbody>\n'
'                    </table>\n'
'                    <div class="row mt-2">\n'
'                        <div class="col-md-4">\n'
'                            <input class="form-control" placeholder="Item name" @bind="newItemName" />\n'
'                        </div>\n'
'                        <div class="col-md-3">\n'
'                            <input type="number" step="0.01" class="form-control" placeholder="Cost" @bind="newItemCost" />\n'
'                        </div>\n'
'                        <div class="col-md-2">\n'
'                            <input type="checkbox" @bind="newItemRequired" /> Required\n'
'                        </div>\n'
'                        <div class="col-md-3">\n'
'                            <button class="btn btn-sm btn-success" @onclick="() => AddAthleteItem(level.Id)">+ Add Item</button>\n'
'                        </div>\n'
'                    </div>\n'
'                </div>\n'
'            </div>\n'
'        }\n'
'    }\n'
'}\n'
'\n'
'@code {\n'
'    private List<Season>? seasons;\n'
'    private List<TeamLevel> teamLevels = new();\n'
'    private List<AthleteItem> athleteItems = new();\n'
'    private int selectedSeasonId;\n'
'    private bool showForm;\n'
'    private TeamLevel? editingLevel;\n'
'    private string formName = "";\n'
'    private int formAthleteCount = 0;\n'
'    private int formPaymentMonths = 5;\n'
'    private string newItemName = "";\n'
'    private decimal newItemCost = 0;\n'
'    private bool newItemRequired = true;\n'
'\n'
'    protected override async Task OnInitializedAsync()\n'
'    {\n'
'        seasons = await Task.FromResult(Db.Seasons.OrderByDescending(s => s.Name).ToList());\n'
'        var active = seasons.FirstOrDefault(s => s.IsActive);\n'
'        if (active != null) { selectedSeasonId = active.Id; await LoadData(); }\n'
'    }\n'
'\n'
'    private async Task OnSeasonChanged(ChangeEventArgs e)\n'
'    {\n'
'        selectedSeasonId = int.TryParse(e.Value?.ToString(), out var id) ? id : 0;\n'
'        await LoadData();\n'
'    }\n'
'\n'
'    private async Task LoadData()\n'
'    {\n'
'        teamLevels = await Task.FromResult(Db.TeamLevels.Where(t => t.SeasonId == selectedSeasonId).ToList());\n'
'        var levelIds = teamLevels.Select(t => t.Id).ToList();\n'
'        athleteItems = await Task.FromResult(Db.AthleteItems.Where(a => levelIds.Contains(a.TeamLevelId)).ToList());\n'
'    }\n'
'\n'
'    private void ShowForm() { editingLevel = null; formName = ""; formAthleteCount = 0; formPaymentMonths = 5; showForm = true; }\n'
'    private void CancelForm() { showForm = false; }\n'
'\n'
'    private void EditLevel(TeamLevel level)\n'
'    {\n'
'        editingLevel = level; formName = level.Name; formAthleteCount = level.AthleteCount; formPaymentMonths = level.PaymentPlanMonths; showForm = true;\n'
'    }\n'
'\n'
'    private async Task SaveLevel()\n'
'    {\n'
'        if (editingLevel == null)\n'
'            Db.TeamLevels.Add(new TeamLevel { Name = formName, AthleteCount = formAthleteCount, PaymentPlanMonths = formPaymentMonths, SeasonId = selectedSeasonId });\n'
'        else\n'
'        {\n'
'            editingLevel.Name = formName; editingLevel.AthleteCount = formAthleteCount; editingLevel.PaymentPlanMonths = formPaymentMonths;\n'
'            Db.TeamLevels.Update(editingLevel);\n'
'        }\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadData();\n'
'        showForm = false;\n'
'    }\n'
'\n'
'    private async Task DeleteLevel(TeamLevel level)\n'
'    {\n'
'        Db.TeamLevels.Remove(level);\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadData();\n'
'    }\n'
'\n'
'    private async Task AddAthleteItem(int levelId)\n'
'    {\n'
'        if (string.IsNullOrWhiteSpace(newItemName)) return;\n'
'        Db.AthleteItems.Add(new AthleteItem { Name = newItemName, Cost = newItemCost, IsRequired = newItemRequired, TeamLevelId = levelId });\n'
'        await Db.SaveChangesAsync();\n'
'        newItemName = ""; newItemCost = 0; newItemRequired = true;\n'
'        await LoadData();\n'
'    }\n'
'\n'
'    private async Task DeleteAthleteItem(AthleteItem item)\n'
'    {\n'
'        Db.AthleteItems.Remove(item);\n'
'        await Db.SaveChangesAsync();\n'
'        await LoadData();\n'
'    }\n'
'}\n'
)

files["Pages/Reports.razor"] = (
'@page "/reports"\n'
'@using GymBudgetApp.Models\n'
'@using GymBudgetApp\n'
'@using Microsoft.EntityFrameworkCore\n'
'@inject AppDbContext Db\n'
'\n'
'<h3>Reports</h3>\n'
'\n'
'@if (seasons == null)\n'
'{\n'
'    <p>Loading...</p>\n'
'}\n'
'else\n'
'{\n'
'    <div class="mb-3">\n'
'        <label>Select Season</label>\n'
'        <select class="form-select w-auto d-inline-block ms-2" @onchange="OnSeasonChanged">\n'
'            <option value="">-- Select Season --</option>\n'
'            @foreach (var s in seasons)\n'
'            {\n'
'                <option value="@s.Id">@s.Name</option>\n'
'            }\n'
'        </select>\n'
'    </div>\n'
'\n'
'    @if (selectedSeasonId > 0 && selectedSeason != null)\n'
'    {\n'
'        <div class="row mb-4">\n'
'            <div class="col-md-3">\n'
'                <div class="card text-white bg-primary">\n'
'                    <div class="card-body">\n'
'                        <h6>Total Budgeted</h6>\n'
'                        <h4>@budgetTotal.ToString("C")</h4>\n'
'                    </div>\n'
'                </div>\n'
'            </div>\n'
'            <div class="col-md-3">\n'
'                <div class="card text-white bg-success">\n'
'                    <div class="card-body">\n'
'                        <h6>Total Actual</h6>\n'
'                        <h4>@actualTotal.ToString("C")</h4>\n'
'                    </div>\n'
'                </div>\n'
'            </div>\n'
'            <div class="col-md-3">\n'
'                <div class="card text-white bg-info">\n'
'                    <div class="card-body">\n'
'                        <h6>Cost Per Athlete</h6>\n'
'                        <h4>@costPerAthlete.ToString("C")</h4>\n'
'                    </div>\n'
'                </div>\n'
'            </div>\n'
'            <div class="col-md-3">\n'
'                <div class="card text-white bg-warning">\n'
'                    <div class="card-body">\n'
'                        <h6>Variance</h6>\n'
'                        <h4>@(budgetTotal - actualTotal).ToString("C")</h4>\n'
'                    </div>\n'
'                </div>\n'
'            </div>\n'
'        </div>\n'
'\n'
'        <h5>Budget vs Actual by Category</h5>\n'
'        <table class="table table-striped mb-4">\n'
'            <thead>\n'
'                <tr><th>Category</th><th>Budgeted</th><th>Actual</th><th>Variance</th></tr>\n'
'            </thead>\n'
'            <tbody>\n'
'                @foreach (var cat in Enum.GetValues<BudgetCategory>())\n'
'                {\n'
'                    var budgeted = lineItems.Where(i => i.Category == cat && !i.IsActual).Sum(i => i.Total);\n'
'                    var actual = lineItems.Where(i => i.Category == cat && i.IsActual).Sum(i => i.Total);\n'
'                    if (budgeted > 0 || actual > 0)\n'
'                    {\n'
'                        <tr>\n'
'                            <td>@cat</td>\n'
'                            <td>@budgeted.ToString("C")</td>\n'
'                            <td>@actual.ToString("C")</td>\n'
'                            <td class="@(budgeted - actual >= 0 ? "text-success" : "text-danger")">\n'
'                                @((budgeted - actual).ToString("C"))\n'
'                            </td>\n'
'                        </tr>\n'
'                    }\n'
'                }\n'
'            </tbody>\n'
'        </table>\n'
'\n'
'        <h5>Team Level Cost Breakdown</h5>\n'
'        @foreach (var level in teamLevels)\n'
'        {\n'
'            var items = athleteItems.Where(i => i.TeamLevelId == level.Id).ToList();\n'
'            var itemsTotal = items.Sum(i => i.Cost);\n'
'            var grandTotal = costPerAthlete + itemsTotal;\n'
'            var monthly = level.PaymentPlanMonths > 0 ? grandTotal / level.PaymentPlanMonths : 0;\n'
'            <div class="card mb-3">\n'
'                <div class="card-header"><h6>@level.Name — @level.AthleteCount athletes</h6></div>\n'
'                <div class="card-body">\n'
'                    <table class="table table-sm">\n'
'                        <tbody>\n'
'                            <tr><td>Individual Share of Team Expenses</td><td>@costPerAthlete.ToString("C")</td></tr>\n'
'                            @foreach (var item in items)\n'
'                            {\n'
'                                <tr><td>@item.Name @(item.IsRequired ? "" : "(optional)")</td><td>@item.Cost.ToString("C")</td></tr>\n'
'                            }\n'
'                        </tbody>\n'
'                        <tfoot>\n'
'                            <tr class="fw-bold"><td>Grand Total</td><td>@grandTotal.ToString("C")</td></tr>\n'
'                            <tr class="text-primary fw-bold"><td>Payment Plan (@level.PaymentPlanMonths months)</td><td>@monthly.ToString("C")/month</td></tr>\n'
'                        </tfoot>\n'
'                    </table>\n'
'                </div>\n'
'            </div>\n'
'        }\n'
'    }\n'
'}\n'
'\n'
'@code {\n'
'    private List<Season>? seasons;\n'
'    private List<BudgetLineItem> lineItems = new();\n'
'    private List<TeamLevel> teamLevels = new();\n'
'    private List<AthleteItem> athleteItems = new();\n'
'    private int selectedSeasonId;\n'
'    private Season? selectedSeason;\n'
'\n'
'    private decimal budgetTotal => lineItems.Where(i => !i.IsActual).Sum(i => i.Total);\n'
'    private decimal actualTotal => lineItems.Where(i => i.IsActual).Sum(i => i.Total);\n'
'    private decimal costPerAthlete => selectedSeason?.AthleteCount > 0 ? budgetTotal / selectedSeason!.AthleteCount : 0;\n'
'\n'
'    protected override async Task OnInitializedAsync()\n'
'    {\n'
'        seasons = await Task.FromResult(Db.Seasons.OrderByDescending(s => s.Name).ToList());\n'
'        var active = seasons.FirstOrDefault(s => s.IsActive);\n'
'        if (active != null) { selectedSeasonId = active.Id; selectedSeason = active; await LoadData(); }\n'
'    }\n'
'\n'
'    private async Task OnSeasonChanged(ChangeEventArgs e)\n'
'    {\n'
'        selectedSeasonId = int.TryParse(e.Value?.ToString(), out var id) ? id : 0;\n'
'        selectedSeason = seasons?.FirstOrDefault(s => s.Id == selectedSeasonId);\n'
'        await LoadData();\n'
'    }\n'
'\n'
'    private async Task LoadData()\n'
'    {\n'
'        lineItems = await Task.FromResult(Db.BudgetLineItems.Where(b => b.SeasonId == selectedSeasonId).ToList());\n'
'        teamLevels = await Task.FromResult(Db.TeamLevels.Where(t => t.SeasonId == selectedSeasonId).ToList());\n'
'        var levelIds = teamLevels.Select(t => t.Id).ToList();\n'
'        athleteItems = await Task.FromResult(Db.AthleteItems.Where(a => levelIds.Contains(a.TeamLevelId)).ToList());\n'
'    }\n'
'}\n'
)

for path, content in files.items():
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    size = os.path.getsize(path)
    print(f"Written {path} ({size} bytes)")
