// <auto-generated />
using System;
using GymBudgetApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymBudgetApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318220651_AddSeasonIsPublished")]
    partial class AddSeasonIsPublished
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("GymBudgetApp.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamLevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamLevelId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("GymBudgetApp.Models.AthleteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamLevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamLevelId");

                    b.ToTable("AthleteItems");
                });

            modelBuilder.Entity("GymBudgetApp.Models.AthleteItemSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleteItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AthleteItemId");

                    b.HasIndex("AthleteId", "AthleteItemId")
                        .IsUnique();

                    b.ToTable("AthleteItemSelections");
                });

            modelBuilder.Entity("GymBudgetApp.Models.BudgetLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntryFeeType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActual")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SeasonGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("MeetId");

                    b.HasIndex("SeasonGroupId");

                    b.HasIndex("SeasonId");

                    b.ToTable("BudgetLineItems");
                });

            modelBuilder.Entity("GymBudgetApp.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonGroupId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("GymBudgetApp.Models.CoachGroupAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonGroupId");

                    b.HasIndex("CoachId", "SeasonGroupId")
                        .IsUnique();

                    b.ToTable("CoachGroupAssignments");
                });

            modelBuilder.Entity("GymBudgetApp.Models.CoachMeetAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeetId");

                    b.HasIndex("CoachId", "MeetId")
                        .IsUnique();

                    b.ToTable("CoachMeetAssignments");
                });

            modelBuilder.Entity("GymBudgetApp.Models.Meet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TravelType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonGroupId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Meets");
                });

            modelBuilder.Entity("GymBudgetApp.Models.MeetGroupAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonGroupId");

                    b.HasIndex("MeetId", "SeasonGroupId")
                        .IsUnique();

                    b.ToTable("MeetGroupAssignments");
                });

            modelBuilder.Entity("GymBudgetApp.Models.MeetTeamLevelAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamLevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamLevelId");

                    b.HasIndex("MeetId", "TeamLevelId")
                        .IsUnique();

                    b.ToTable("MeetTeamLevelAssignments");
                });

            modelBuilder.Entity("GymBudgetApp.Models.MileageEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Miles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RatePerMile")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("MeetId");

                    b.ToTable("MileageEntries");
                });

            modelBuilder.Entity("GymBudgetApp.Models.ParentLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.ToTable("ParentLinks");
                });

            modelBuilder.Entity("GymBudgetApp.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GymBudgetApp.Models.PerDiemEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("MeetId");

                    b.ToTable("PerDiemEntries");
                });

            modelBuilder.Entity("GymBudgetApp.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleteCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AthleteItemLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoachLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableMileage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePerDiem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableTeamLevels")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeetLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamLevelLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("GymBudgetApp.Models.SeasonGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonGroups");
                });

            modelBuilder.Entity("GymBudgetApp.Models.SeasonNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonNotes");
                });

            modelBuilder.Entity("GymBudgetApp.Models.SharedFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIncludedInBudget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("SharedFees");
                });

            modelBuilder.Entity("GymBudgetApp.Models.SharedFeeTeamLevelAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SharedFeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamLevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamLevelId");

                    b.HasIndex("SharedFeeId", "TeamLevelId")
                        .IsUnique();

                    b.ToTable("SharedFeeTeamLevelAssignments");
                });

            modelBuilder.Entity("GymBudgetApp.Models.TeamLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleteCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentPlanMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("TeamLevels");
                });

            modelBuilder.Entity("GymBudgetApp.Models.TeamLevelGroupAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamLevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonGroupId");

                    b.HasIndex("TeamLevelId", "SeasonGroupId")
                        .IsUnique();

                    b.ToTable("TeamLevelGroupAssignments");
                });

            modelBuilder.Entity("GymBudgetApp.Models.UserImportPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserImportPins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymBudgetApp.Models.Athlete", b =>
                {
                    b.HasOne("GymBudgetApp.Models.TeamLevel", "TeamLevel")
                        .WithMany("Athletes")
                        .HasForeignKey("TeamLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamLevel");
                });

            modelBuilder.Entity("GymBudgetApp.Models.AthleteItem", b =>
                {
                    b.HasOne("GymBudgetApp.Models.TeamLevel", "TeamLevel")
                        .WithMany("AthleteItems")
                        .HasForeignKey("TeamLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamLevel");
                });

            modelBuilder.Entity("GymBudgetApp.Models.AthleteItemSelection", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Athlete", "Athlete")
                        .WithMany("ItemSelections")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBudgetApp.Models.AthleteItem", "AthleteItem")
                        .WithMany()
                        .HasForeignKey("AthleteItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("AthleteItem");
                });

            modelBuilder.Entity("GymBudgetApp.Models.BudgetLineItem", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Coach", "Coach")
                        .WithMany("BudgetLineItems")
                        .HasForeignKey("CoachId");

                    b.HasOne("GymBudgetApp.Models.Meet", "Meet")
                        .WithMany("BudgetLineItems")
                        .HasForeignKey("MeetId");

                    b.HasOne("GymBudgetApp.Models.SeasonGroup", "SeasonGroup")
                        .WithMany("BudgetLineItems")
                        .HasForeignKey("SeasonGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GymBudgetApp.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Meet");

                    b.Navigation("Season");

                    b.Navigation("SeasonGroup");
                });

            modelBuilder.Entity("GymBudgetApp.Models.Coach", b =>
                {
                    b.HasOne("GymBudgetApp.Models.SeasonGroup", "SeasonGroup")
                        .WithMany("Coaches")
                        .HasForeignKey("SeasonGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GymBudgetApp.Models.Season", "Season")
                        .WithMany("Coaches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("SeasonGroup");
                });

            modelBuilder.Entity("GymBudgetApp.Models.CoachGroupAssignment", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Coach", "Coach")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBudgetApp.Models.SeasonGroup", "SeasonGroup")
                        .WithMany("CoachAssignments")
                        .HasForeignKey("SeasonGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("SeasonGroup");
                });

            modelBuilder.Entity("GymBudgetApp.Models.CoachMeetAssignment", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Coach", "Coach")
                        .WithMany("MeetAssignments")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBudgetApp.Models.Meet", "Meet")
                        .WithMany("CoachAssignments")
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Meet");
                });

            modelBuilder.Entity("GymBudgetApp.Models.Meet", b =>
                {
                    b.HasOne("GymBudgetApp.Models.SeasonGroup", "SeasonGroup")
                        .WithMany("Meets")
                        .HasForeignKey("SeasonGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GymBudgetApp.Models.Season", "Season")
                        .WithMany("Meets")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("SeasonGroup");
                });

            modelBuilder.Entity("GymBudgetApp.Models.MeetGroupAssignment", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Meet", "Meet")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBudgetApp.Models.SeasonGroup", "SeasonGroup")
                        .WithMany("MeetAssignments")
                        .HasForeignKey("SeasonGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meet");

                    b.Navigation("SeasonGroup");
                });

            modelBuilder.Entity("GymBudgetApp.Models.MeetTeamLevelAssignment", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Meet", "Meet")
                        .WithMany("TeamLevelAssignments")
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBudgetApp.Models.TeamLevel", "TeamLevel")
                        .WithMany("MeetAssignments")
                        .HasForeignKey("TeamLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meet");

                    b.Navigation("TeamLevel");
                });

            modelBuilder.Entity("GymBudgetApp.Models.MileageEntry", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBudgetApp.Models.Meet", "Meet")
                        .WithMany()
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Meet");
                });

            modelBuilder.Entity("GymBudgetApp.Models.ParentLink", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("GymBudgetApp.Models.Payment", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("GymBudgetApp.Models.PerDiemEntry", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Coach", "Coach")
                        .WithMany("PerDiemEntries")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBudgetApp.Models.Meet", "Meet")
                        .WithMany("PerDiemEntries")
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Meet");
                });

            modelBuilder.Entity("GymBudgetApp.Models.SeasonGroup", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Season", "Season")
                        .WithMany("SeasonGroups")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GymBudgetApp.Models.SeasonNote", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Season", "Season")
                        .WithMany("SeasonNotes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GymBudgetApp.Models.SharedFee", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Season", "Season")
                        .WithMany("SharedFees")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GymBudgetApp.Models.SharedFeeTeamLevelAssignment", b =>
                {
                    b.HasOne("GymBudgetApp.Models.SharedFee", "SharedFee")
                        .WithMany("TeamLevelAssignments")
                        .HasForeignKey("SharedFeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBudgetApp.Models.TeamLevel", "TeamLevel")
                        .WithMany("SharedFeeAssignments")
                        .HasForeignKey("TeamLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedFee");

                    b.Navigation("TeamLevel");
                });

            modelBuilder.Entity("GymBudgetApp.Models.TeamLevel", b =>
                {
                    b.HasOne("GymBudgetApp.Models.Season", "Season")
                        .WithMany("TeamLevels")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GymBudgetApp.Models.TeamLevelGroupAssignment", b =>
                {
                    b.HasOne("GymBudgetApp.Models.SeasonGroup", "SeasonGroup")
                        .WithMany("TeamLevelAssignments")
                        .HasForeignKey("SeasonGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymBudgetApp.Models.TeamLevel", "TeamLevel")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("TeamLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeasonGroup");

                    b.Navigation("TeamLevel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymBudgetApp.Models.Athlete", b =>
                {
                    b.Navigation("ItemSelections");
                });

            modelBuilder.Entity("GymBudgetApp.Models.Coach", b =>
                {
                    b.Navigation("BudgetLineItems");

                    b.Navigation("GroupAssignments");

                    b.Navigation("MeetAssignments");

                    b.Navigation("PerDiemEntries");
                });

            modelBuilder.Entity("GymBudgetApp.Models.Meet", b =>
                {
                    b.Navigation("BudgetLineItems");

                    b.Navigation("CoachAssignments");

                    b.Navigation("GroupAssignments");

                    b.Navigation("PerDiemEntries");

                    b.Navigation("TeamLevelAssignments");
                });

            modelBuilder.Entity("GymBudgetApp.Models.Season", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Meets");

                    b.Navigation("SeasonGroups");

                    b.Navigation("SeasonNotes");

                    b.Navigation("SharedFees");

                    b.Navigation("TeamLevels");
                });

            modelBuilder.Entity("GymBudgetApp.Models.SeasonGroup", b =>
                {
                    b.Navigation("BudgetLineItems");

                    b.Navigation("CoachAssignments");

                    b.Navigation("Coaches");

                    b.Navigation("MeetAssignments");

                    b.Navigation("Meets");

                    b.Navigation("TeamLevelAssignments");
                });

            modelBuilder.Entity("GymBudgetApp.Models.SharedFee", b =>
                {
                    b.Navigation("TeamLevelAssignments");
                });

            modelBuilder.Entity("GymBudgetApp.Models.TeamLevel", b =>
                {
                    b.Navigation("AthleteItems");

                    b.Navigation("Athletes");

                    b.Navigation("GroupAssignments");

                    b.Navigation("MeetAssignments");

                    b.Navigation("SharedFeeAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
